name: build my custom tokyo60 HHKB framework
on:
  push:
    branches:
      - gatsby

permissions:
  contents: read

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: Phoscur/QMK-compile@v1
        with:
          keyboard: "tokyokeyboard/tokyo60"
          keymap: "gatsby"
          layout_src: "gatsby"
          fork: junyi-hou/qmk_frimware
          branch: gatsby

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: built-images
          path: artifacts
